def generate_report(filename, ats_analysis):
    report = f"""
==============================
      ATS RESUME REPORT
==============================

Resume File:
{filename}

--------------------------------

{ats_analysis}

--------------------------------

Generated by Resume AI Agent
"""

    return report